name: food_image_classifier_demo
channels:
- fastai
- pytorch
- conda-forge
- defaults
dependencies:
- fastcore>=1.0.0
- torchvision>=0.7
- fastprogress>=0.2.4
- fastai==2.0.13
- pillow
- pytorch>=1.6.0
- voila
- packaging
- ipywidgets==7.5.1
